import {
  diagramIRToDrawioXml,
  diagramIRToMermaid,
} from "@/lib/diagrams/diagram-ir";
import type { ConversionProvider, DiagramIR, ReviewDocument } from "@/lib/types";

export function createMockProvider(): ConversionProvider {
  return {
    name: "mock",
    async convert(input) {
      const now = new Date().toISOString();
      const firstPage = input.pages[0];
      const firstPageImage = input.assets.find(
        (asset) => asset.kind === "page-image",
      );
      const diagramIR: DiagramIR = {
        title: "Mock workflow diagram",
        nodes: [
          { id: "A", label: "Receive document", kind: "process" },
          { id: "B", label: "Extract content", kind: "process" },
          { id: "C", label: "Diagram found?", kind: "decision" },
          { id: "D", label: "Review Mermaid", kind: "process" },
          { id: "E", label: "Review Markdown", kind: "process" },
        ],
        edges: [
          { id: "e1", from: "A", to: "B" },
          { id: "e2", from: "B", to: "C" },
          { id: "e3", from: "C", to: "D", label: "Yes" },
          { id: "e4", from: "C", to: "E", label: "No" },
        ],
        groups: [],
        unclearNotes: [],
        confidence: 0.8,
      };
      const mermaid = diagramIRToMermaid(diagramIR);

      const document: ReviewDocument = {
        id: input.id,
        title: `${input.sourceFileName} conversion`,
        sourceFileName: input.sourceFileName,
        sourceFileType: input.fileType,
        createdAt: now,
        updatedAt: now,
        sections: [
          {
            id: "sec_mock_summary_1",
            type: "paragraph",
            title: "Mock conversion summary",
            sourcePage: firstPage?.pageNumber ?? 1,
            originalText: firstPage?.text,
            generatedMarkdown:
              firstPage?.text ||
              "TODO: No text was extracted from the source document.",
            reviewStatus: "pending",
          },
          {
            id: "sec_mock_diagram_2",
            type: "diagram",
            title: "Mock workflow diagram",
            sourcePage: firstPage?.pageNumber ?? 1,
            sourceImage: firstPageImage?.path ?? "",
            generatedMarkdown: `\`\`\`mermaid\n${mermaid}\n\`\`\``,
            reviewStatus: "pending",
            format: "mermaid",
            generatedCode: mermaid,
            drawioXml: diagramIRToDrawioXml(diagramIR),
            diagramIR,
          },
        ],
        assets: input.assets.map((asset) => ({
          id: asset.id,
          path: asset.path,
          mimeType: asset.mimeType,
          title: asset.kind,
          sourcePage: asset.sourcePage,
        })),
        warnings: input.warnings,
      };

      return document;
    },
    async regenerateSection(_input, section, options) {
      const instruction = options?.instruction?.trim();

      if (section.type === "diagram") {
        const marker = instruction
          ? `\n  %% Instruction: ${instruction}`
          : "\n  %% Regenerated by mock provider";
        return {
          ...section,
          generatedCode: `${section.generatedCode}${marker}`,
          generatedMarkdown: `\`\`\`mermaid\n${section.generatedCode}${marker}\n\`\`\``,
          reviewStatus: "pending",
        };
      }

      const marker = instruction
        ? `\n\nTODO: Reviewer instruction: ${instruction}`
        : "\n\nTODO: Regenerated by mock provider for review.";
      return {
        ...section,
        generatedMarkdown: `${section.generatedMarkdown}${marker}`,
        reviewStatus: "pending",
      };
    },
  };
}
